"""
Seeds ~25 high-priority government & PSU leads into b2b_leads
with division = "government".
Safe to call multiple times — skips companies already in DB.
"""
from __future__ import annotations
from datetime import datetime
from sqlalchemy.orm import Session
from app.models.models import B2BLead

GOV_LEADS: list[dict] = [
    # ── Defence ──────────────────────────────────────────────────────────────
    {
        "company": "Canteen Stores Department (CSD) — HQ",
        "contact_name": "Director Procurement",
        "contact_title": "Director (Procurement)",
        "email": "csdprocurement@gov.in",
        "phone": "011-23015598",
        "city": "Mumbai",
        "industry": "Defence / Government",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "West",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://csdcanteen.gov.in",
        "estimated_value": 5000000.0,
        "priority": "HIGH",
        "score": 90,
        "qualification_notes": "CSD supplies FMCG to all military canteens across India. Annual rate contract for coffee — one approval = national supply.",
        "recommended_action": "Send rate-contract proposal + FSSAI & MSME certificates. Call Director Procurement.",
        "segment": "government",
    },
    # ── Railways ─────────────────────────────────────────────────────────────
    {
        "company": "IRCTC — Catering & Tourism Division",
        "contact_name": "GM (Catering Services)",
        "contact_title": "General Manager, Catering",
        "email": "gm.catering@irctc.co.in",
        "phone": "011-23311263",
        "city": "New Delhi",
        "industry": "Railways / Government",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.irctc.co.in",
        "estimated_value": 3000000.0,
        "priority": "HIGH",
        "score": 88,
        "qualification_notes": "IRCTC empanels coffee suppliers for pantry cars, station cafés, and executive lounges. High-volume sachet demand.",
        "recommended_action": "Apply for IRCTC vendor empanelment. Send product spec and FSSAI certificate.",
        "segment": "government",
    },
    # ── GeM Registration ─────────────────────────────────────────────────────
    {
        "company": "GeM SPU (Government e-Marketplace) — Procurement Cell",
        "contact_name": "CEO GeM",
        "contact_title": "CEO",
        "email": "support@gem.gov.in",
        "phone": "1800-419-3436",
        "city": "New Delhi",
        "industry": "Government Marketplace",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://gem.gov.in",
        "estimated_value": 10000000.0,
        "priority": "HIGH",
        "score": 95,
        "qualification_notes": "Register as GeM seller for category 'Food & Beverages > Coffee'. Opens all 60,000+ government buyers instantly.",
        "recommended_action": "Complete GeM seller registration immediately. Upload product catalogue, pricing, FSSAI, GST.",
        "segment": "government",
    },
    # ── Oil PSUs ─────────────────────────────────────────────────────────────
    {
        "company": "Indian Oil Corporation — Corporate HQ",
        "contact_name": "Head, Corporate Procurement",
        "contact_title": "Deputy GM (Procurement)",
        "email": "procurement@iocl.co.in",
        "phone": "011-26265000",
        "city": "New Delhi",
        "industry": "Oil & Gas / PSU",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.iocl.com",
        "estimated_value": 2000000.0,
        "priority": "HIGH",
        "score": 82,
        "qualification_notes": "IOCL has 50,000+ employees across offices, refineries and COCO outlets. Pantry coffee is a regular procurement item.",
        "recommended_action": "Apply through GeM or direct vendor registration on iocl.com. Send pantry supply proposal.",
        "segment": "government",
    },
    {
        "company": "ONGC — Corporate Pantry Services",
        "contact_name": "DGM (Admin & Services)",
        "contact_title": "Deputy GM Administration",
        "email": "admin@ongc.co.in",
        "phone": "0135-2460860",
        "city": "Dehradun",
        "industry": "Oil & Gas / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.ongcindia.com",
        "estimated_value": 1500000.0,
        "priority": "HIGH",
        "score": 80,
        "qualification_notes": "ONGC offshore platforms need freeze-dried coffee for shelf stability. Onshore offices also have pantry procurement.",
        "recommended_action": "Register on GeM. Send freeze-dried coffee proposal emphasising shelf stability for remote locations.",
        "segment": "government",
    },
    {
        "company": "Bharat Petroleum Corporation — Retail Division",
        "contact_name": "DGM (Admin)",
        "contact_title": "Deputy GM, Administration",
        "email": "admin.hq@bharatpetroleum.in",
        "phone": "022-22713000",
        "city": "Mumbai",
        "industry": "Oil & Gas / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "West",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.bharatpetroleum.in",
        "estimated_value": 1200000.0,
        "priority": "MEDIUM",
        "score": 72,
        "qualification_notes": "BPCL COCO outlets and corporate pantry procurement via GeM.",
        "recommended_action": "Register on GeM. Approach BPCL's Mumbai HQ with pantry supply proposal.",
        "segment": "government",
    },
    # ── Power Sector ─────────────────────────────────────────────────────────
    {
        "company": "NTPC Limited — Corporate Procurement",
        "contact_name": "DGM (Procurement)",
        "contact_title": "Deputy GM, Materials Management",
        "email": "procurement@ntpc.co.in",
        "phone": "011-24360100",
        "city": "New Delhi",
        "industry": "Power / PSU",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.ntpc.co.in",
        "estimated_value": 500000.0,
        "priority": "HIGH",
        "score": 78,
        "qualification_notes": "NTPC has townships and 7,000 MW plants. Regular pantry coffee procurement through GeM.",
        "recommended_action": "List on GeM under NTPC buyer. Send pantry proposal to admin@ntpc.co.in.",
        "segment": "government",
    },
    {
        "company": "Power Grid Corporation of India",
        "contact_name": "AGM (Administration)",
        "contact_title": "Asst. GM, Administration",
        "email": "admin@powergridindia.com",
        "phone": "0124-2571700",
        "city": "Gurugram",
        "industry": "Power / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.powergridindia.com",
        "estimated_value": 400000.0,
        "priority": "MEDIUM",
        "score": 68,
        "qualification_notes": "PGCIL manages 1,80,000 km transmission network. Many remote substations + corporate HQ pantry needs.",
        "recommended_action": "Register on GeM. Reach out to admin.pgcil@nic.in for direct pantry quote.",
        "segment": "government",
    },
    # ── Coal & Mining ────────────────────────────────────────────────────────
    {
        "company": "Coal India Limited — CMD Office",
        "contact_name": "Director (Personnel)",
        "contact_title": "Director, Personnel & HR",
        "email": "dirpersonnel@coalindia.in",
        "phone": "033-22890017",
        "city": "Kolkata",
        "industry": "Mining / PSU",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "East",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.coalindia.in",
        "estimated_value": 1200000.0,
        "priority": "HIGH",
        "score": 80,
        "qualification_notes": "CIL has 300+ mines with canteens, townships and offices. Annual rate contracts for pantry supply.",
        "recommended_action": "Contact procurement@coalindia.in with pantry supply rate chart. Also raise GeM bid.",
        "segment": "government",
    },
    # ── Steel ────────────────────────────────────────────────────────────────
    {
        "company": "SAIL — Steel Authority of India (Corporate HQ)",
        "contact_name": "GM (Administration)",
        "contact_title": "General Manager, Administration",
        "email": "admin@sail.in",
        "phone": "011-24367481",
        "city": "New Delhi",
        "industry": "Steel / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.sail.co.in",
        "estimated_value": 800000.0,
        "priority": "MEDIUM",
        "score": 72,
        "qualification_notes": "SAIL has steel plants in Bhilai, Rourkela, Bokaro, Durgapur, Burnpur with townships. Large canteen procurement.",
        "recommended_action": "Send rate proposal to admin@sail.in. Target canteen supply at plant locations.",
        "segment": "government",
    },
    # ── Banks ────────────────────────────────────────────────────────────────
    {
        "company": "State Bank of India — Apex Training Institute",
        "contact_name": "Principal (ATI)",
        "contact_title": "Principal, Apex Training Institute",
        "email": "ati.gurgaon@sbi.co.in",
        "phone": "0124-2678600",
        "city": "Gurugram",
        "industry": "Banking / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.sbi.co.in",
        "estimated_value": 600000.0,
        "priority": "HIGH",
        "score": 76,
        "qualification_notes": "SBI ATI trains 15,000+ officers/year. Guest house, canteen, meeting room coffee are high volume. Multiple training institutes across India.",
        "recommended_action": "Contact ATI admin for pantry supply quote. Also approach SBI State Bank Staff College, Hyderabad.",
        "segment": "government",
    },
    {
        "company": "Punjab National Bank — Staff College",
        "contact_name": "Principal (Staff College)",
        "contact_title": "Principal, PNB Staff College",
        "email": "staffcollege@pnb.co.in",
        "phone": "0522-2788101",
        "city": "Lucknow",
        "industry": "Banking / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.pnbindia.in",
        "estimated_value": 300000.0,
        "priority": "MEDIUM",
        "score": 64,
        "qualification_notes": "PNB Staff College trains bank officers. Hostel canteen and guest house procurement.",
        "recommended_action": "Send pantry supply proposal to staffcollege@pnb.co.in.",
        "segment": "government",
    },
    {
        "company": "Bank of Baroda — Baroda Academy",
        "contact_name": "GM (HRD)",
        "contact_title": "General Manager, HRD",
        "email": "academy@bankofbaroda.com",
        "phone": "0265-2361852",
        "city": "Vadodara",
        "industry": "Banking / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "West",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.bankofbaroda.in",
        "estimated_value": 280000.0,
        "priority": "MEDIUM",
        "score": 60,
        "qualification_notes": "Baroda Academy and regional training centres procure pantry items for residential programmes.",
        "recommended_action": "Call academy@bankofbaroda.com with pantry coffee rate sheet.",
        "segment": "government",
    },
    # ── Airports ─────────────────────────────────────────────────────────────
    {
        "company": "Airports Authority of India — Executive Lounges",
        "contact_name": "GM (Commercial)",
        "contact_title": "General Manager, Commercial",
        "email": "commercial@aai.aero",
        "phone": "011-24632950",
        "city": "New Delhi",
        "industry": "Aviation / Government",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.aai.aero",
        "estimated_value": 400000.0,
        "priority": "MEDIUM",
        "score": 70,
        "qualification_notes": "AAI manages 100+ airports. Executive lounges, corporate offices, staff cafeterias all use instant coffee.",
        "recommended_action": "Register on GeM under AAI buyer. Send premium positioning pitch for lounge coffee supply.",
        "segment": "government",
    },
    # ── Cooperative / Kendriya Bhandar ───────────────────────────────────────
    {
        "company": "Kendriya Bhandar — Corporate Office",
        "contact_name": "MD & CEO",
        "contact_title": "Managing Director & CEO",
        "email": "kb@nic.in",
        "phone": "011-23748360",
        "city": "New Delhi",
        "industry": "Government Retail",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.kendriyabhandar.in",
        "estimated_value": 2000000.0,
        "priority": "HIGH",
        "score": 85,
        "qualification_notes": "Kendriya Bhandar has 120+ retail stores supplying Central Govt employees. Brand listing = instant retail access to government consumers.",
        "recommended_action": "Apply as approved supplier. Submit product samples + pricing. Call 011-23748360.",
        "segment": "government",
    },
    # ── Telecom PSU ──────────────────────────────────────────────────────────
    {
        "company": "BSNL — Corporate Office Pantry",
        "contact_name": "DGM (Admin)",
        "contact_title": "Deputy GM, Administration",
        "email": "admin.co@bsnl.co.in",
        "phone": "011-23734411",
        "city": "New Delhi",
        "industry": "Telecom / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.bsnl.co.in",
        "estimated_value": 500000.0,
        "priority": "MEDIUM",
        "score": 62,
        "qualification_notes": "BSNL has exchanges across all districts of India. Pan-India pantry coffee procurement potential.",
        "recommended_action": "Register on GeM. Send pantry supply proposal to admin.co@bsnl.co.in.",
        "segment": "government",
    },
    # ── NLC / NHPC ───────────────────────────────────────────────────────────
    {
        "company": "NLC India Limited — Township Canteen",
        "contact_name": "GM (Admin & HR)",
        "contact_title": "General Manager, Administration",
        "email": "gmadmin@nlcindia.com",
        "phone": "04142-252281",
        "city": "Neyveli",
        "industry": "Mining & Power / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "South",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.nlcindia.com",
        "estimated_value": 600000.0,
        "priority": "MEDIUM",
        "score": 66,
        "qualification_notes": "NLC Township in Neyveli has ~30,000 residents. Large canteen procurement — both South India filter coffee and instant coffee.",
        "recommended_action": "Reach out to admin with pantry coffee proposal. Mention Tamil Nadu distribution reach.",
        "segment": "government",
    },
    # ── State Tourism ────────────────────────────────────────────────────────
    {
        "company": "India Tourism Development Corporation (ITDC)",
        "contact_name": "Director (Operations)",
        "contact_title": "Director, Hotel Operations",
        "email": "operations@theashokgroup.com",
        "phone": "011-26110101",
        "city": "New Delhi",
        "industry": "Hospitality / Government",
        "company_size": "Enterprise",
        "contact_persona": None,
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.theashokgroup.com",
        "estimated_value": 700000.0,
        "priority": "MEDIUM",
        "score": 72,
        "qualification_notes": "ITDC operates The Ashok and other 5-star government hotels. Premium in-room and restaurant coffee supply opportunity.",
        "recommended_action": "Send premium positioning pitch. Position as luxury Indian brand for state hospitality.",
        "segment": "government",
    },
    # ── Health ───────────────────────────────────────────────────────────────
    {
        "company": "AIIMS New Delhi — Hospital Administration",
        "contact_name": "Dean (Administration)",
        "contact_title": "Dean, Administration",
        "email": "deanadmin@aiims.edu",
        "phone": "011-26588500",
        "city": "New Delhi",
        "industry": "Healthcare / Government",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.aiims.edu",
        "estimated_value": 400000.0,
        "priority": "MEDIUM",
        "score": 65,
        "qualification_notes": "AIIMS has staff canteens, resident doctors' hostels, and guest houses. Low-acid coffee well suited for healthcare setting.",
        "recommended_action": "Send low-acid health positioning pitch. Contact through GeM or direct to admin.",
        "segment": "government",
    },
    # ── Universities ─────────────────────────────────────────────────────────
    {
        "company": "IIT Delhi — Hostel & Mess Administration",
        "contact_name": "Dean of Students",
        "contact_title": "Dean of Students Affairs",
        "email": "dos@admin.iitd.ac.in",
        "phone": "011-26591723",
        "city": "New Delhi",
        "industry": "Education / Government",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://home.iitd.ac.in",
        "estimated_value": 350000.0,
        "priority": "MEDIUM",
        "score": 64,
        "qualification_notes": "IIT Delhi has 10,000+ students + faculty. Multiple hostels, student mess, faculty club. GeM procurement.",
        "recommended_action": "Register on GeM. Target IIT Delhi, IIT Bombay, IIT Madras hostel mess supply.",
        "segment": "government",
    },
    # ── Defence Production ───────────────────────────────────────────────────
    {
        "company": "Ordnance Factory Board — Guest House & Canteen",
        "contact_name": "GM (Admin)",
        "contact_title": "General Manager, Administration",
        "email": "ofbhq@nic.in",
        "phone": "033-22483567",
        "city": "Kolkata",
        "industry": "Defence Production / PSU",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "East",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://ofb.gov.in",
        "estimated_value": 500000.0,
        "priority": "MEDIUM",
        "score": 65,
        "qualification_notes": "OFB has 41 ordnance factories across India with canteens and guest houses.",
        "recommended_action": "Send pantry coffee proposal to ofbhq@nic.in. Also register on GeM.",
        "segment": "government",
    },
    # ── Space ────────────────────────────────────────────────────────────────
    {
        "company": "ISRO — Space Applications Centre Canteen",
        "contact_name": "Admin Officer",
        "contact_title": "Administrative Officer",
        "email": "admin@sac.isro.gov.in",
        "phone": "079-26914000",
        "city": "Ahmedabad",
        "industry": "Space / Government",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "West",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.isro.gov.in",
        "estimated_value": 300000.0,
        "priority": "MEDIUM",
        "score": 62,
        "qualification_notes": "ISRO campuses (Bengaluru HQ, SAC Ahmedabad, SDSC Sriharikota) have large cafeteria requirements.",
        "recommended_action": "Register on GeM. Send pantry supply quote to admin offices at Bengaluru HQ.",
        "segment": "government",
    },
    # ── State Government ─────────────────────────────────────────────────────
    {
        "company": "Punjab Civil Secretariat — Administration",
        "contact_name": "OSD (Administration)",
        "contact_title": "Officer on Special Duty, Administration",
        "email": "admin@punjab.gov.in",
        "phone": "0172-2740006",
        "city": "Chandigarh",
        "industry": "State Government",
        "company_size": "Enterprise",
        "contact_persona": "Admin Manager",
        "region": "North",
        "division": "government",
        "lead_source": "Government Directory",
        "website": "https://www.punjabgovt.gov.in",
        "estimated_value": 250000.0,
        "priority": "MEDIUM",
        "score": 60,
        "qualification_notes": "Punjab Civil Secretariat has hundreds of offices. Proximity to Abohar (Hiten's base) is advantageous for supply.",
        "recommended_action": "Reach out directly — proximity from Abohar is a competitive advantage for same-day delivery.",
        "segment": "government",
    },
]


def seed_government_leads(db: Session) -> dict:
    """Insert government leads that don't already exist. Returns summary."""
    inserted = 0
    skipped = 0
    for lead_data in GOV_LEADS:
        exists = db.query(B2BLead).filter(
            B2BLead.company == lead_data["company"]
        ).first()
        if exists:
            skipped += 1
            continue
        lead = B2BLead(
            company=lead_data["company"],
            contact_name=lead_data.get("contact_name"),
            contact_title=lead_data.get("contact_title"),
            email=lead_data.get("email"),
            phone=lead_data.get("phone"),
            city=lead_data.get("city"),
            industry=lead_data.get("industry", "Government"),
            company_size=lead_data.get("company_size", "Enterprise"),
            contact_persona=lead_data.get("contact_persona"),   # unknown until told
            region=(lead_data.get("region") or ""),   # do not place a business by default
            division=lead_data.get("division", "government"),
            lead_source=(lead_data.get("lead_source") or "UNKNOWN_SOURCE"),
            website=lead_data.get("website"),
            estimated_value=lead_data.get("estimated_value", 0.0),
            priority=lead_data.get("priority", "MEDIUM"),
            score=lead_data.get("score", 60),
            qualification_notes=lead_data.get("qualification_notes"),
            recommended_action=lead_data.get("recommended_action"),
            segment=lead_data.get("segment", "government"),
            status="QUALIFIED",
            intent_tier="Warm",
        )
        db.add(lead)
        inserted += 1
    db.commit()
    return {"inserted": inserted, "skipped": skipped, "total": len(GOV_LEADS)}
