"""CallResult: one structured row per AI call attempt.

SQLite-safe and idempotent: a NEW table only (no ALTER of existing tables),
created with ``checkfirst=True`` so startup, the worker and the backfill
script can all call :func:`ensure_call_results_table` any number of times.
"""
from __future__ import annotations

import weakref
from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Float, Integer, JSON, String, Text, inspect,
)

from app.database.database import Base


class CallResult(Base):
    __tablename__ = "call_results"

    id = Column(Integer, primary_key=True)
    # Stable id for this attempt. Generated by Python before dispatch
    # ("call_ref") and echoed back by the voice agent; falls back to the
    # provider id / a lead+attempt key for callers that do not send one.
    call_id = Column(String(96), nullable=False, unique=True, index=True)
    lead_id = Column(Integer, nullable=False, index=True)
    provider = Column(String(40), nullable=True)
    provider_call_id = Column(String(96), nullable=True, index=True)
    room_name = Column(String(160), nullable=True)
    sip_call_id = Column(String(160), nullable=True)
    attempt_number = Column(Integer, nullable=True)

    # OPEN while the call is in flight; FINAL once any termination path
    # (or the reconciler) wrote an outcome.
    status = Column(String(12), nullable=False, default="OPEN", index=True)
    started_at = Column(DateTime, nullable=True, index=True)
    answered_at = Column(DateTime, nullable=True)
    ended_at = Column(DateTime, nullable=True)
    duration_seconds = Column(Float, nullable=True)

    connected = Column(Boolean, nullable=True)
    reached_decision_maker = Column(Boolean, nullable=True)
    outcome = Column(String(32), nullable=True, index=True)       # RESULT_OUTCOMES
    raw_outcome = Column(String(40), nullable=True)                # provider / FSM key
    termination_reason = Column(String(60), nullable=True)
    sip_status_code = Column(Integer, nullable=True)

    objections = Column(JSON, nullable=True)                       # ["PRICE", ...]
    drop_off_turn = Column(Integer, nullable=True)
    drop_off_stage = Column(String(24), nullable=True)
    turn_count = Column(Integer, nullable=True)
    user_turn_count = Column(Integer, nullable=True)
    language = Column(String(12), nullable=True)
    script_variant = Column(String(64), nullable=True, index=True)
    opener_variant = Column(String(64), nullable=True, index=True)
    sentiment = Column(String(12), nullable=True)
    rude_or_complaint = Column(Boolean, nullable=True)

    next_action = Column(String(40), nullable=True)
    next_action_at = Column(DateTime, nullable=True)
    summary = Column(Text, nullable=True)
    lessons = Column(JSON, nullable=True)                          # {"worked": [], "failed": []}
    evidence = Column(JSON, nullable=True)                         # matched phrases, sources
    confidence = Column(String(20), nullable=True)                 # OBSERVED|INFERRED|LOW_CONFIDENCE|HUMAN_CORRECTED
    source = Column(String(24), nullable=True)                     # voice_agent|engine|reconciler|founder

    # Segment snapshot at dial time, so aggregation does not depend on later
    # edits to the lead row.
    business_type = Column(String(60), nullable=True, index=True)
    city = Column(String(80), nullable=True, index=True)
    hour_bucket = Column(String(16), nullable=True)
    brief = Column(JSON, nullable=True)                            # what the agent was told

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# Engines (weakly held) whose call_results table is known to exist.
_ENSURED: "weakref.WeakSet" = weakref.WeakSet()


def call_results_table_exists(bind) -> bool:
    try:
        return bool(inspect(bind).has_table(CallResult.__tablename__))
    except Exception:  # noqa: BLE001
        return False


def ensure_call_results_table(bind) -> bool:
    """Create ``call_results`` if missing. Idempotent; never alters data."""
    engine = getattr(bind, "engine", bind)
    if engine in _ENSURED:
        return True
    try:
        CallResult.__table__.create(bind=bind, checkfirst=True)
        _ENSURED.add(engine)
        return True
    except Exception:  # noqa: BLE001
        return call_results_table_exists(bind)


def ensure_for_session(db) -> bool:
    """Ensure inside the caller's session/connection (safe with StaticPool)."""
    try:
        conn = db.connection()
    except Exception:  # noqa: BLE001
        return False
    if conn.engine in _ENSURED:
        return True
    try:
        CallResult.__table__.create(bind=conn, checkfirst=True)
        _ENSURED.add(conn.engine)
        return True
    except Exception:  # noqa: BLE001
        return call_results_table_exists(conn)


def results_table_ready(db) -> bool:
    """Read-path check: never issues DDL (safe inside the dial path, where a
    CREATE TABLE would open a write transaction across the network call)."""
    try:
        conn = db.connection()
    except Exception:  # noqa: BLE001
        return False
    if conn.engine in _ENSURED:
        return True
    ok = call_results_table_exists(conn)
    if ok:
        _ENSURED.add(conn.engine)
    return ok
